sample_name = "Friesach"
last_preset_index = 1

[[presets]]
preset = 1

  [[presets.divisions]]
  name = "Pedale"
  stops = [
    "Untersatz 32'",
    "Contrabass 16'",
    "Subbass 16'",
    "Octavbass 8'"
  ]

  [[presets.divisions]]
  name = "Hauptwerk"
  stops = [
    "Praestant 16'",
    "Principal 8'",
    "Holzflöte 8'",
    "Röhrflöte 8'"
  ]

  [[presets.divisions]]
  name = "Schwellwerk"
  stops = [
    "Bourdon 16'",
    "Principal 8'",
    "Nachthorn Gedackt 8'",
    "Corno dolce 8'"
  ]
  tremolo = true

  [[presets.couplers]]
  name = "I/P"
  from_division = "Hauptwerk"
  to_division = "Pedal"

  [[presets.modyfiers]]
  modyfier = "Split"
  settings = [
    { split_note = 69, input_channel = 0, output_channel = 2 }
  ]

[[presets]]
preset = 2

  [[presets.divisions]]
  name = "Pedale"
  stops = [
    "Untersatz 32'",
    "Contrabass 16'",
    "Subbass 16'",
    "Octavbass 8'",
    "Gedackt 8'"
  ]

  [[presets.divisions]]
  name = "Hauptwerk"
  stops = [
    "Praestant 16'",
    "Principal 8'",
    "Holzflöte 8'",
    "Röhrflöte 8'",
    "Gambe 8'"
  ]

  [[presets.divisions]]
  name = "Schwellwerk"
  stops = [
    "Bourdon 16'",
    "Principal 8'",
    "Nachthorn Gedackt 8'",
    "Corno dolce 8'",
    "Viola 8'"
  ]
  tremolo = true

  [[presets.couplers]]
  name = "I/P"
  from_division = "Hauptwerk"
  to_division = "Pedal"

  [[presets.modyfiers]]
  modyfier = "Split"
  settings = [
    { split_note = 60, input_channel = 1, output_channel = 3 }
  ]